### ISSUE TITLE
Empty calibration parameter support

### ISSUE THREAD

**Issue by dboulware** [NTIA/scos-actions#103]
Calibration should be updated to handle empty calibration parameters. When no calibration parameters are supplied the default calibration data ca be put directly in calibration_data. In addition the example cal files should be deleted and a default cal file should be added to scos-sensor that supports any sigan by using empty calibration parameters.

**Comment by aromanielloNTIA** [comment]
I really like the idea of removing the example cal files and replacing them with something that will support any sigan. However, I think there is a need to enforce calibration parameters. Maybe we can require that SignalAnalyzerInterface classes define which calibration parameters are required for a particular sigan. We should avoid a situation where SCOS can apply calibration data when it is not accurate to do so, e.g., if the measurement frequency differs from the calibration frequency, we need to make sure that the calibration data is not used to scale the measurement.

**Comment by aromanielloNTIA** [comment]
Closing this as it is done after #106

Still pending some changes in scos-sensor (currently drafted as NTIA/scos-sensor#264)
