### ISSUE TITLE
Antenna path not reset after Y-Factor Calibration

### ISSUE THREAD

**Issue by aromanielloNTIA** [NTIA/scos-actions#35]
## Issue

When running the Y-Factor calibration action, the preselector is switched first to the noise diode on path, then to the noise diode off path.

If the Y-Factor action is run, then a measurement action is run, the measurement action needs to set the antenna path. Otherwise, the switch is still set to the noise diode path, and the measurement will not be performed correctly.

## Proposed Solution

I see two solutions to this:

1. Update the Y-Factor action to read the preselector's RF path at the start, then at the end of the action, reset the RF path to whatever it was before.
2. Update all measurement actions to include preselector configuration so that the correct path is used.

Option 1 has the benefit of not touching other actions, but could still leave the preselector in the wrong state for a given measurement action.

Option 2 seems better, but requires a preselector (using the ITS Preselector package) to run any action (which may not be an issue)

## Temporary Workaround

This can be worked around in the meantime by manually setting the preselector state using its web interface before running a measurement action.

**Comment by aromanielloNTIA** [comment]
@dboulware thoughts?

**Comment by dboulware** [comment]
Addressed in https://github.com/NTIA/scos-actions/pull/36 which makes actions set rf_path.
